### ISSUE TITLE
Does `watch` work with objects?

### ISSUE THREAD

**Issue by frederikhors** [svecosystem/runed#119]
### Describe the bug

Even if you click mulitple times the button `console.log()` popup just one time.

### Reproduction

https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACl1QvW6DMBB-ldOpg5EQTYcuFEjbMUM6dIwzEGOIVWMj-2gVWbx7ZaMGqcPJuvv-zhewV1p6LE8BTTtKLPFtmjBHuk2x8d9Sk8QcvZ2diJPKC6cmarjhpMbJOoIAPy2JKyzQOzsCRzcb2b3uiqfnYsfxJVJjaUkgrOkUKWughgdPLUkWlixSDKd-NiJhZIdBy2M7SpZBSHq6K4u4KNTwf1DXwPHdXjjCHjge7NVwhPJvmNZY1qC0LzuxDOpm8znnwE5bl8AUDpHjrZaFtgPjuMozEK3WsuOYrd7xqR63-5i7Vwnh8PlxLDw5ZQbV39gdypbq4ppYUVFdZiJrwBqhlfiqw3aJJZ1cXFszSIg_jmErvcEcR9upXskOS3KzXM7LL-0d0VjbAQAA

### System Info

```bash
"svelte": "5.0.0-next.184"
```

### Severity

blocking all usage of WithRunes

**Comment by huntabyte** [comment]
Hey @frederikhors! 

As mentioned in the comments of #120, this is a feature, not a bug.

You'll see you get the same behavior with a regular `$effect`: [REPL](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE2VQwWrDMAz9FSEKTaBk3WGXrEm3HXvoDjvOO6SOnJo5drCVjRL878MpS2E7SKCn9_QkTai0oYDl-4S26QlLfB4G3CBfhlSELzJMuMHgRi8TsgvS64FrYQXrfnCeYYLvhuUZIijvehDoR0vt07a4fyi2Ah8TNYUhBulsq1k7CxWsAjdM2RTzRLGC1Wjl3GPXdYaOTU9ZDtOs50VZpEWhgr9AVYHAF3cSCHsQeHBnKxDKX3BeI16NVqQUSc6yHKr6n8FSBmeoMK7L1lc-yMYYatf5PCplu7u7_cMuE0qYDm-vxyKw17bT6pItrTzuTr5OMctPI7Oz4Kw0Wn5W0-3yOL9YnhvbEaQLk9mVXuMGe9dqpanFkv1I8SP-AMpl4bnLAQAA)

To get the behavior you're looking for, you need to leverage `$state.snapshot()` which will cause it to track the object itself rather than the individual properties: [REPL](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE3WRPW-DMBCG_8rpFCkgIZoOXWigH2OGdOhYdyDmAKtgI_toFSH_98rQJE2lDjf4Pp731esJa9WRw-xtQl32hBk-DQMmyMchPNwndUyYoDOjlaGzddKqgQuhBat-MJZhgq-SZQseamt6EGhHTdXjJr29SzcC78NqqI4YpNGVYmU05LByXDJFk4_DihZcj1rOMzZN09G-7CmKYZrv-XyZBqOQw99GnoPAZ3MQCA8gcGdaLRCyU3O24RehFdU1SY6iGPLiJLDYSZ0uB9cajs78-GzAmY7SzjTRegGALfV6Hvt4Ic9J_HD_ByZwpXxFXrL8A97eXGLXZ04G0-71ZZ86tko3qj7-kvDbgy1CzeeHkdloMFp2Sn7k0yVgP_-kbEvdEIQgg9iyXmCCvalUrajCjO1I_t1_A2TqNcEyAgAA)

**Comment by Not-Jayden** [comment]
I question if this could still be supported with a `deep` option in the config, as I also found this behaviour unintuitive at first glance, though I get it just maps to how `$effect()` behaves.

I think adding the ability to easily deeply track state changes like we've become familiar with from Svelte 4 would be a really nice additional benefit/motivation to using `watch()` over `$effect()`. 

But also maybe this should just be proposed as a Svelte 5 thing 🤷‍♂️

**Comment by frederikhors** [comment]
@huntabyte can we add a `deep` option to it?

**Comment by huntabyte** [comment]
I don't particularly like the idea of adding the `deep` as we want users of this library to understand Svelte 5. If there was some significant work to do to make this happen, then potentially, but it's almost equal in terms of code you have to write:

```ts
{ deep: true }
// vs
`$state.snapshot()`
```

and you get the benefit of understanding how Svelte 5 works.

Happy to have my mind changed if @TGlide or @AdrianGonz97 disagree with me here.

**Comment by frederikhors** [comment]
I think you're right. You convinced me.
